/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

using System;
using System.Collections.Generic;
using System.Linq;
					
public class Program
{
	public static void Main()
	{
		var prev = 1;
		var cur = 2;
		var temp = 0;
		var intList = new List<int>();

		while (cur <= 4000000)
		{
			if (cur % 2 == 0)
				intList.Add(cur);
			
			temp = prev + cur;
			prev = cur;
			cur = temp;
		}
		
		Console.WriteLine(intList.Sum());
	}
}